# Generated by Django 5.2.7 on 2025-10-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_type', models.CharField(choices=[('CC', 'Cedula'), ('ID', 'Id')], max_length=2)),
                ('id_number', models.CharField(max_length=10)),
                ('credit_value', models.IntegerField()),
                ('interest', models.FloatField()),
                ('months', models.IntegerField()),
                ('adviser', models.CharField()),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'form',
            },
        ),
    ]
