# Generated by Django 5.2.7 on 2025-10-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_form',
            name='adviser',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='m_form',
            name='id_number',
            field=models.IntegerField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='m_form',
            name='id_type',
            field=models.CharField(choices=[('CC', 'Cedula'), ('ID', 'Id')]),
        ),
        migrations.AlterField(
            model_name='m_form',
            name='last_name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='m_form',
            name='name',
            field=models.CharField(max_length=35),
        ),
    ]
